name: R Package CI

on:
  push:
    branches:
      - main  # or specify any branch you want to monitor
  pull_request:
    branches:
      - main  # or specify the branch for PRs

jobs:
  check_install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Defining the matrix of operating systems

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Install dependencies
    - name: Install dependencies
      run: |
        if (Sys.info()['sysname'] == 'Windows') {
          install.packages('devtools')
          devtools::install_deps()
        } else {
          install.packages('devtools')
          devtools::install_deps()
        }

    # Run R CMD check
    - name: Run R CMD check
      run: |
        R CMD check .

    # Run R CMD INSTALL
    - name: Run R CMD INSTALL
      run: |
        R CMD INSTALL .
