name: R Package CI

on:
  push:
    branches:
      - main  # or specify any branch you want to monitor
  pull_request:
    branches:
      - main  # or specify the branch for PRs

jobs:
  check_install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Defining the matrix of operating systems

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Rocker R image
    - name: Set up Rocker R
      uses: rocker/r-ver@v4 # You can specify the R version here, e.g., v4.1.0

    # Install pak to handle dependencies
    - name: Install pak (if not already installed)
      run: |
        if (!requireNamespace("pak", quietly = TRUE)) {
          install.packages("pak")
        }

    # Install dependencies using pak
    - name: Install dependencies using pak
      run: |
        R -e "pak::pkg_install()"

    # Run R CMD check
    - name: Run R CMD check
      run: |
        if ($RUNNER_OS -eq 'Windows') {
          # Workaround for PowerShell on Windows
          Rterm.exe CMD check .
        } else {
          R CMD check .
        }

    # Run R CMD INSTALL
    - name: Run R CMD INSTALL
      run: |
        R CMD INSTALL .
